server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: true

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true

resilience4j.circuitbreaker:
  instances:
    findById:
      slidingWindowSize: 1
      waitDurationInOpenState: 10000
#      ignoreExceptions:
#        - com.company.users.exception.UserNotFoundException
#      recordExceptions:
#        - java.net.SocketTimeoutException
#        - java.net.ConnectException